# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions
name: Build and deploy Python project to Azure Function App - CAS-checker-v3
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'        # chemin du projet Functions (racine du repo)
  PYTHON_VERSION: '3.12'                     # version de Python utilisée pour le build
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # requis pour azure/login avec OIDC
      contents: read         # requis pour actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      # Éventuellement : ici tu peux ajouter des tests unitaires
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D22EBD6EAD11448CA92FF9057DE9BDF0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA089CE9AF0F4AB5AA067404A4F46BEA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DEF23B0D3484089BC0004D87A2D2533 }}
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'aip-function-zendesk-put-prod'
          package: .
          scm-do-build-during-deployment: true
          enable-oryx-build: true